/*
 * fpm_sqrt.c -- Q15 fixed-point square root.
 *
 * Reconstructed from dsplibs.o fpm_sqrt.c, .text 0x0a9d70-0x0a9df5, table at
 * .rodata 0x0c520.
 *
 * Part of the `fpm_*` fixed-point maths layer used by the V.22 and fax
 * datapumps.  Fixed point throughout, so the equivalence criterion is
 * bit-exact with zero tolerance -- see docs/findings.md.
 *
 * Method
 * ------
 * Normalise the input into [0x4000, 0xffff] by shifting left, counting the
 * shifts as a base-2 exponent.  Square root halves the exponent, so an odd
 * exponent is made even by shifting the mantissa down one place and letting
 * the table absorb the leftover factor of sqrt(2).  The mantissa then indexes
 * a 192-entry lookup table, and the result is shifted down by half the
 * exponent.
 *
 * Table derivation
 * ----------------
 * The index is ((m + 64) >> 7) - 64, so entry i corresponds to a mantissa of
 * (i + 64) * 128, i.e. a Q15 fraction of (i + 64) / 256.  The table is then
 * simply that fraction's square root in Q15, truncated:
 *
 *     table[i] = floor(32768 * sqrt((i + 64) / 256.0))
 *
 * fpm_sqrt_table_generate() below implements exactly that, and the unit test
 * checks it reproduces all 192 original entries.  The generator is the
 * maintainable artefact; the extracted bytes are only the reference.
 *
 * Domain, and a one-past-the-end read in the original
 * ---------------------------------------------------
 * Callers pass Q15 values, 0x0000..0x7fff.  Over that domain the normalised
 * mantissa lands in [0x4000, 0x7fff], so the index runs 64..192 for an even
 * exponent and 0..63 for an odd one.  The maximum index is therefore 192 --
 * but the original's table has only 192 entries, indices 0..191.
 *
 * So the original reads one element past the end of its own table, and it does
 * so during completely normal operation: 85 of the 32768 Q15 inputs hit it.
 * What it reads is the first entry of FPM_div_table, which immediately follows
 * in .rodata and happens to hold 32768 -- which is *exactly* the mathematically
 * correct value for sqrt_table[192], since sqrt((192+64)/256) = sqrt(1) = 1.
 *
 * The overrun therefore returned the right answer by coincidence, and the real
 * defect is just that the table was declared one entry too short.  This
 * reconstruction adds the missing 193rd entry, generated by the same formula as
 * every other entry.  That is bit-exact with the original across the whole Q15
 * domain while being correct by construction rather than by luck.
 *
 * Above 0x7fff the index can reach 448 and there is no defensible value to
 * return, so this version clamps.  No caller passes such values; the
 * differential test covers 0x0000..0x7fff.
 */

#include <math.h>

#include "dsplib/fpm.h"

/*
 * 193 entries, not the 192 the original declared -- see "Domain" above.
 */
#define FPM_SQRT_TABLE_SIZE 193

/*
 * floor(32768 * sqrt((i + 64) / 256)) for i in [0, 193).
 * Extracted from the original object; regenerated and checked by the test.
 */
static const unsigned short fpm_sqrt_table[FPM_SQRT_TABLE_SIZE] = {
	16384, 16511, 16638, 16763, 16888, 17011, 17134, 17256,
	17377, 17498, 17617, 17736, 17854, 17971, 18087, 18203,
	18317, 18432, 18545, 18658, 18770, 18881, 18992, 19102,
	19211, 19320, 19429, 19536, 19643, 19750, 19856, 19961,
	20066, 20170, 20274, 20377, 20480, 20582, 20683, 20784,
	20885, 20985, 21085, 21184, 21283, 21381, 21479, 21577,
	21673, 21770, 21866, 21962, 22057, 22152, 22246, 22341,
	22434, 22528, 22620, 22713, 22805, 22897, 22988, 23079,
	23170, 23260, 23350, 23440, 23529, 23618, 23707, 23795,
	23883, 23971, 24058, 24145, 24232, 24318, 24404, 24490,
	24576, 24661, 24746, 24830, 24914, 24999, 25082, 25166,
	25249, 25332, 25415, 25497, 25579, 25661, 25742, 25824,
	25905, 25986, 26066, 26147, 26227, 26307, 26386, 26465,
	26545, 26624, 26702, 26781, 26859, 26937, 27014, 27092,
	27169, 27246, 27323, 27400, 27476, 27553, 27629, 27704,
	27780, 27855, 27930, 28005, 28080, 28155, 28229, 28303,
	28377, 28451, 28525, 28598, 28672, 28745, 28817, 28890,
	28963, 29035, 29107, 29179, 29251, 29322, 29394, 29465,
	29536, 29607, 29678, 29748, 29819, 29889, 29959, 30029,
	30099, 30168, 30238, 30307, 30376, 30445, 30514, 30583,
	30651, 30720, 30788, 30856, 30924, 30991, 31059, 31126,
	31194, 31261, 31328, 31395, 31461, 31528, 31595, 31661,
	31727, 31793, 31859, 31925, 31990, 32056, 32121, 32186,
	32251, 32316, 32381, 32446, 32510, 32575, 32639, 32703,
	32768,	/* index 192: absent from the original's table - see above */
};

unsigned short
FPM_sqrt(unsigned short x)
{
	unsigned exponent = 0;
	unsigned mantissa;
	int index;

	if (x == 0)
		return 0;

	/*
	 * Left-normalise so the mantissa's top bit lands in bit 14 or 15.
	 * Inputs already at or above 0x4000 need no shifting.
	 */
	mantissa = x;
	while (mantissa <= 0x3fff) {
		mantissa = (mantissa << 1) & 0xffff;
		exponent++;
	}

	/*
	 * Halving an odd exponent would leave a stray factor of sqrt(2).
	 * Shift the mantissa down instead and let the table cover the wider
	 * input range -- which is why the table spans a factor of four in its
	 * argument but only two in its result.
	 */
	if (exponent & 1)
		mantissa >>= 1;

	index = (int)((mantissa + 64) >> 7) - 64;

	/*
	 * Within Q15 the index cannot leave [0, 192] and the table now covers
	 * it.  The clamp guards only the out-of-contract inputs above 0x7fff,
	 * where the original reads arbitrarily far past its table.
	 */
	if (index < 0)
		index = 0;
	if (index >= FPM_SQRT_TABLE_SIZE)
		index = FPM_SQRT_TABLE_SIZE - 1;

	return (unsigned short)(fpm_sqrt_table[index] >> (exponent >> 1));
}

/*
 * 32-bit square root, sharing the same table.
 *
 * Structurally identical to FPM_sqrt: left-normalise, halve the exponent,
 * index the quarter-scale table, shift the result down.  It normalises until
 * the value exceeds 0x1fffffff and takes bits 15 upward as the mantissa.
 *
 * The interesting difference is that **this one bounds-checks**:
 *
 *     if ((unsigned short)index > 0xbf) index = 0xbf;
 *
 * clamping to entry 191, the last of the original's 192.  FPM_sqrt, indexing
 * the same table from the same author, does not -- it reads entry 192 and
 * lands in FPM_div_table (deviation D1).  So the bound was known; the 16-bit
 * version simply missed it.
 *
 * Note the clamp is *unsigned*, so a negative index wraps to a large unsigned
 * value and also clamps to 191 rather than to 0.  That is reachable: an input
 * at or above 0x80000000 gives `x >> 15 >= 0x10000`, which truncates to a
 * small or zero mantissa and drives the index negative.
 *
 * That truncation is reproduced rather than corrected.  Unlike FPM_sqrt's
 * Q15 contract (deviation D2), there is no domain here that rules the case
 * out: FPM_rms is the only caller, its accumulator overflows 0x80000000 at 73
 * full-scale samples, and every call site passes a runtime sample count -- so
 * reachability cannot be established statically, and matching the blob is the
 * only defensible choice.
 */
unsigned short
FPM_sqrt_dp(unsigned int x)
{
	unsigned exponent = 0;
	unsigned mantissa;
	int index;

	if (x == 0)
		return 0;

	while (x <= 0x1fffffffu) {
		x += x;
		exponent++;
	}

	/* Truncated to 16 bits, which is where large inputs lose their top bit. */
	mantissa = (unsigned short)(x >> 15);

	if (exponent & 1)
		mantissa >>= 1;

	index = (int)((mantissa + 64) >> 7) - 64;
	if ((unsigned short)index > 0xbf)
		index = 0xbf;

	return (unsigned short)(fpm_sqrt_table[index] >> (exponent >> 1));
}

/*
 * Regenerate one table entry from the design parameters.  Kept alongside the
 * table so the derivation stays checkable: the unit test regenerates all 192
 * entries and compares against the extracted originals.
 */
unsigned short
FPM_sqrt_table_generate(int index)
{
	/* Deliberately double precision: the original was generated offline. */
	double frac = (index + 64) / 256.0;
	return (unsigned short)(32768.0 * sqrt(frac));
}

unsigned short
FPM_sqrt_table_entry(int index)
{
	return (index >= 0 && index < FPM_SQRT_TABLE_SIZE)
		? fpm_sqrt_table[index] : 0;
}

int
FPM_sqrt_table_size(void)
{
	return FPM_SQRT_TABLE_SIZE;
}
