#!/usr/bin/env python3
"""Observe unchanged Gentoo cc1 allocation decisions with raw-object controls.

Requires Docker, host GDB with Python, and the three validated historical
inputs generated by gcc3_reload_reproduce.py. No inferior state is modified.
"""
import argparse
import hashlib
import json
import shlex
import subprocess
from pathlib import Path
import experiment_toolchain as tc

ROOT = Path(__file__).resolve().parents[1]


def run(command, folder, name):
    with (folder/(name+'.log')).open('w') as log:
        subprocess.run(command, cwd=folder, stdout=log, stderr=subprocess.STDOUT, check=True)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--reproduction-dir', type=Path,
                        default=ROOT/'build/gcc3-reload-reproduction')
    args = parser.parse_args()
    reproduction = args.reproduction_dir.resolve()
    prior = json.loads((reproduction/'results.json').read_text())
    assert prior['controls']['raw_production'] and prior['controls']['diagnostic_pairs'] == 3
    config = prior['config']
    image = config.splitlines()[0].split(' ', 1)[1]
    flags = shlex.split(next(line[6:] for line in config.splitlines() if line.startswith('flags ')))
    flags = ['-I/src/include' if f == '-Iinclude' else '/src/'+f if f == 'tools/toolchain/period_compat.h' else f for f in flags]
    out = ROOT/'build/gcc3-allocation-observation'
    out.mkdir(parents=True, exist_ok=True)
    executable = out/'cc1'
    with executable.open('wb') as stream:
        subprocess.run(['docker', 'run', '--rm', '--platform', 'linux/386', image,
                        'cat', '/usr/libexec/gcc/i386-pc-linux-gnu/3.4.2/cc1'], stdout=stream, check=True)
    executable.chmod(0o755)
    tc.print_identity(image, tc.GENTOO_COMPILER_PATH, True)
    run(['gdb', '--version'], out, 'gdb-identity')
    run(['ldd', str(executable)], out, 'host-runtime')
    results = {'config': config, 'source_revision': prior['revision'],
               'compiler_sha256': hashlib.sha256(executable.read_bytes()).hexdigest(),
               'cells': {}}
    for label in ('full', 'extracted', 'quiet'):
        folder = out/label
        folder.mkdir(exist_ok=True)
        original = reproduction/(label+'-plain')/'V34TX.c'
        text = original.read_bytes()
        assert hashlib.sha256(text).hexdigest() == prior['cells'][label+'-plain']['source_sha256']
        (folder/'V34TX.c').write_bytes(text)
        for name in ('observe.json', 'observed.o', 'observed.s', 'plain.s'):
            (folder/name).unlink(missing_ok=True)
        target = '/work/'+label
        shell = 'cd '+shlex.quote(target)+' && '+tc.compile_shell(tc.GENTOO_COMPILER_PATH, flags+['-v', '-save-temps'], target+'/reference.o', target+'/V34TX.c')
        command = tc.docker_prefix(image, ROOT, out, True)+['/bin/sh', '-c', shell]
        run(command, folder, 'driver')
        assert (folder/'reference.o').read_bytes() == (reproduction/(label+'-plain')/'candidate.o').read_bytes(), label+' preparation drift'
        log = (folder/'driver.log').read_text().splitlines()
        cc1 = shlex.split(next(line for line in log if '/cc1 -fpreprocessed' in line))
        assembler = shlex.split(next(line for line in log if '/bin/as ' in line))
        cc1[0] = str(executable)
        cc1[cc1.index('-o')+1] = 'plain.s'
        run(cc1, folder, 'plain')
        plain_command = list(cc1)
        cc1[cc1.index('-o')+1] = 'observed.s'
        gdb = ['gdb', '-q', '-batch', '-ex', 'set pagination off', '-ex',
               'source '+str(ROOT/'tools/gcc3_alloc_observe_gdb.py'), '--args']+cc1
        run(gdb, folder, 'gdb')
        assert (folder/'V34TX.s').read_bytes() == (folder/'plain.s').read_bytes() == (folder/'observed.s').read_bytes(), label+' assembly drift'
        assembler[assembler.index('-o')+1] = target+'/observed.o'
        assembler[-1] = 'observed.s'
        assemble = tc.docker_prefix(image, ROOT, out, True)+['/bin/sh', '-c', 'cd '+shlex.quote(target)+' && '+shlex.join(assembler)]
        run(assemble, folder, 'assembler')
        assert (folder/'observed.o').read_bytes() == (folder/'reference.o').read_bytes(), label+' debugger object drift'
        events = json.loads((folder/'observe.json').read_text())
        combined = [e for e in events if e['kind']=='allocation' and e['members']==[77, 73]]
        assert [(e['args']['class'], e['return']) for e in combined] == [(1, -1), (12, 1)], label+' coalescing/AREG fallback control'
        evictions = [e for e in events if e['kind']=='home_change' and e['reg'] in (73,77)]
        assert [(e['reg'], e['home'], e['frames'][0]) for e in evictions] == [(73, -1, 'find_reg'), (77, -1, 'find_reg')], label+' global eviction control'
        assert all(e['frames'][1]=='global_alloc' for e in evictions)
        results['cells'][label] = {'source_sha256': hashlib.sha256(text).hexdigest(),
                                  'object_sha256': hashlib.sha256((folder/'observed.o').read_bytes()).hexdigest(),
                                  'commands': [command, plain_command, gdb, assemble], 'events': events,
                                  'raw_object_control': True}
        (out/'results.json').write_text(json.dumps(results, indent=2)+'\n')
        print(label, len(events), 'events; raw object, coalescing and global eviction controls pass', flush=True)
    results['controls'] = {'preparation_objects': 3, 'assembly_triples': 3,
                           'debugger_objects': 3, 'coalescing_graphs': 3, 'global_eviction_graphs': 3}
    (out/'results.json').write_text(json.dumps(results, indent=2)+'\n')
    print('3/3 cells pass all preparation, assembly, object and allocator controls')


if __name__ == '__main__':
    main()
