#!/usr/bin/env python3
"""
Emit src/core/rc_coeffs.c from dsplibs.o's FixedRC coefficient banks.

The extracted bytes are kept verbatim so the reconstruction stays bit-identical
to the original and Tier-1 differential testing holds exactly.  They are not
the maintainable form: docs/coefficients.md records the recovered design, which
is what a retarget to another sample rate should regenerate from.

Layout, per RcFixed_Resample's addressing (see docs/coefficients.md):
`up` polyphase branches of `taps` int16 Q14 each, phase-major.

Usage:
    gen_rc_coeffs.py <obj> [-o src/core/rc_coeffs.c]
"""

import argparse
import struct
import subprocess

# mode -> (coefficient address, taps), from the jump table at .rodata 0x10f14.
BANKS = {
    2:  (0x10c80, 36), 3:  (0x10b40, 32), 4:  (0x10c80, 36), 5:  (0x10aa0, 68),
    6:  (0x10b40, 32), 7:  (0x10a00, 68), 8:  (0x10880, 46), 9:  (0x107e0, 68),
    10: (0x10060, 40), 11: (0x0fda0, 68), 12: (0x0fc80, 28), 13: (0x0faa0, 58),
    14: (0x0f9a0, 42), 15: (0x0f8e0, 48), 16: (0x0f5e0, 38), 17: (0x0f440, 68),
    18: (0x0f140, 38), 19: (0x0ef00, 32),
}
UP = [4, 1, 6, 5, 6, 1, 5, 1, 4, 1, 24, 5, 5, 4, 3, 2, 10, 3, 10, 9]

HEADER = '''/*
 * rc_coeffs.c -- FixedRC polyphase resampler coefficient banks.
 *
 * GENERATED by tools/gen_rc_coeffs.py from dsplibs.o .rodata -- do not edit.
 *
 * These are the original extracted coefficients, kept verbatim so the
 * reconstruction is bit-identical to the blob and Tier-1 differential testing
 * holds exactly.
 *
 * They are NOT the maintainable form.  docs/coefficients.md records the
 * recovered design (Kaiser-windowed sinc, cutoff ~0.94 of the binding
 * Nyquist) which is what an 8 kHz retarget should regenerate from.  A clean
 * regeneration measures about 9.6 dB better in the stopband than these bytes,
 * because the original carries a flat +-2 LSB coefficient noise floor.
 *
 * Storage, per RcFixed_Resample's addressing: `up` polyphase branches of
 * `taps` int16 Q14 each, phase-major.  Branch p is coeff[p*taps ..].
 */

#include "dsplib/fixedrc.h"
'''


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("obj")
    ap.add_argument("-o", "--output", default="src/core/rc_coeffs.c")
    args = ap.parse_args()

    blob = subprocess.run(
        ["objcopy", "-O", "binary", "--only-section", ".rodata",
         args.obj, "/dev/stdout"], capture_output=True, check=True).stdout

    # Several modes share a bank; emit each array once.
    uniq = {}
    for m, (a, t) in BANKS.items():
        uniq.setdefault(a, (t, UP[m], []))[2].append(m)

    out = [HEADER]
    for a in sorted(uniq, reverse=True):
        taps, up, modes = uniq[a]
        vals = list(struct.unpack_from("<%dh" % (taps * up), blob, a))
        out.append("/* modes %s: %d taps x %d phases, Q14 */"
                   % (", ".join(map(str, sorted(modes))), taps, up))
        out.append("const short rc_coeff_%05x[%d] = {" % (a, len(vals)))
        for i in range(0, len(vals), 10):
            out.append("\t" + ", ".join("%d" % v for v in vals[i:i + 10]) + ",")
        out.append("};\n")

    out.append("/* mode -> bank.  Modes 0 and 1 use a different state layout and are\n"
               " * not part of this table; RcFixed_Create rejects them here. */")
    out.append("const struct rc_bank rc_banks[RCFIXED_NMODES] = {")
    for m in range(20):
        if m in BANKS:
            a, t = BANKS[m]
            out.append("\t{ rc_coeff_%05x, %d },\t/* mode %d */" % (a, t, m))
        else:
            out.append("\t{ 0, 0 },\t/* mode %d - separate state layout */" % m)
    out.append("};")

    with open(args.output, "w") as f:
        f.write("\n".join(out) + "\n")
    print("wrote %s: %d unique banks" % (args.output, len(uniq)))


if __name__ == "__main__":
    main()
