/*
 * t_v23bwch.c -- differential test of the V.23 backward-channel demodulator.
 *
 * This is the first V.23 object that has to be driven with a real signal to
 * do anything at all.  It will not emit a single bit until FPM_TONE_detect
 * has seen 390 Hz for ten consecutive blocks, so a test built on synthetic
 * input -- an impulse, a ramp, noise -- would compare two demodulators that
 * both sat in the acquisition state for ever and agreed perfectly about it.
 *
 * So the stimulus is generated by v23FP_tx configured for the backward
 * channel, which is the same thing the far end of a real call would be doing
 * and is already proved against the blob by t_v23tx.  A leading run of mark
 * bits stands in for the idle condition that brings carrier up.
 *
 * Three things are compared after every block: the return code, the bits and
 * how many of them, and the object itself byte for byte apart from the four
 * pointers whose values are addresses.  The last of those is what catches a
 * demodulator that produced the right bits by a different route -- a settle
 * counter one out, an energy accumulator that saturates differently -- which
 * would agree for a while and then diverge somewhere with no test at all.
 */

#include <stdio.h>
#include <string.h>

#include "harness.h"
#include "dsplib/v23fp.h"

extern void *ref_BwChDem_Create(void *bw, const void *cfg);
extern void ref_BwChDem_Delete(void *bw);
extern short ref_BwChDem_Progress(void *bw, short *samples, short count,
				  int *bits, int *nbits);

#define BW_MARK		390
#define BW_SPACE	450

static const short bw_period[3] = { 107, 107, 106 };

/* Coverage. */
static int saw_waiting;		/* returned 1, still acquiring       */
static int saw_demodulating;	/* returned 0, carrier up            */
static int saw_bits;		/* at least one bit came out         */
static int saw_one, saw_zero;	/* and both values did               */
static int saw_given_up;	/* returned 2                        */

/*
 * The four fields that hold addresses.  Their contents are compared
 * separately where they point at something; `tone` and `agc.cfg.alpha/beta`
 * are covered by t_fpm_tone and t_fpm_agc.
 */
static int
is_pointer_field(unsigned off)
{
	return (off >= __builtin_offsetof(struct bwchdem, tone)
		&& off < __builtin_offsetof(struct bwchdem, tone) + 4)
	    || (off >= __builtin_offsetof(struct bwchdem, iir_coeff)
		&& off < __builtin_offsetof(struct bwchdem, iir_coeff) + 4)
	    || (off >= __builtin_offsetof(struct bwchdem, iir_state)
		&& off < __builtin_offsetof(struct bwchdem, iir_state) + 4)
	    || (off >= __builtin_offsetof(struct bwchdem, agc)
		       + __builtin_offsetof(struct fpm_agc_cfg, alpha)
		&& off < __builtin_offsetof(struct bwchdem, agc)
			 + __builtin_offsetof(struct fpm_agc_cfg, beta) + 4);
}

static void
compare_obj(const char *what, const struct bwchdem *ours, const void *refp)
{
	const unsigned char *a = (const unsigned char *)ours;
	const unsigned char *b = (const unsigned char *)refp;
	const struct bwchdem *ref = (const struct bwchdem *)refp;
	unsigned i;

	for (i = 0; i < sizeof(struct bwchdem); i++) {
		if (is_pointer_field(i))
			continue;
		diff_eq_int(what, a[i], b[i], i);
	}
	/* The heap-allocated filter state, through the two pointers. */
	for (i = 0; i < 12; i++)
		diff_eq_int("iir state[%ld]", ours->iir_state[i],
			    ref->iir_state[i], i);
}

/*
 * Generate `n` samples of backward-channel FSK from `bits`, using the
 * transmitter this tree already proves against the blob.
 */
static void
generate(short *out, int n, const int *bits, int nbits)
{
	struct v23tx *tx;
	int at = 0;
	int done = 0;

	tx = v23FP_tx_create(NULL, BW_MARK, BW_SPACE, 3, bw_period, 0);
	while (done < n) {
		int chunk = n - done > 160 ? 160 : n - done;
		int used = 0;

		v23FP_tx_progress(tx, out + done, chunk, bits + at, &used);
		done += chunk;
		at += used;
		if (at + 32 > nbits)
			at = 0;
	}
	v23FP_tx_delete(tx);
}

/*
 * Run one signal through both demodulators, `block` samples at a time.
 * Returns how many bits came out of ours.
 */
static int
run(const char *what, const short *signal, int n, int block, int silence_limit)
{
	struct v23_cfg cfg;
	struct bwchdem *ours;
	void *ref;
	short buf_a[512], buf_b[512];
	int bits_a[64], bits_b[64];
	int total = 0;
	int at;

	memset(&cfg, 0, sizeof(cfg));
	cfg.silence_limit = silence_limit;

	ours = BwChDem_Create(NULL, &cfg);
	ref = ref_BwChDem_Create(NULL, &cfg);
	compare_obj("after create", ours, ref);

	for (at = 0; at + block <= n; at += block) {
		short rc_a, rc_b;
		int na = -1, nb = -1;
		int i;

		/* Each side needs its own copy: the block is filtered in place. */
		memcpy(buf_a, signal + at, block * sizeof(short));
		memcpy(buf_b, signal + at, block * sizeof(short));
		memset(bits_a, 0x5a, sizeof(bits_a));
		memset(bits_b, 0x5a, sizeof(bits_b));

		rc_a = BwChDem_Progress(ours, buf_a, (short)block, bits_a, &na);
		rc_b = ref_BwChDem_Progress(ref, buf_b, (short)block, bits_b,
					    &nb);

		diff_eq_int("return code", rc_a, rc_b, at / block);
		diff_eq_int("bits produced", na, nb, at / block);
		for (i = 0; i < block; i++)
			diff_eq_int(what, buf_a[i], buf_b[i], i);
		for (i = 0; i < na && i < 64; i++) {
			diff_eq_int("bit[%ld]", bits_a[i], bits_b[i], i);
			if (bits_a[i])
				saw_one++;
			else
				saw_zero++;
		}
		compare_obj("object after a block", ours, ref);

		if (rc_a == 0)
			saw_demodulating++;
		else if (rc_a == 1)
			saw_waiting++;
		else
			saw_given_up++;
		total += na;
		if (na > 0)
			saw_bits++;
		if (rc_a == 2)
			break;
	}

	BwChDem_Delete(ours);
	ref_BwChDem_Delete(ref);
	return total;
}

#define NSAMP 24000		/* three seconds at 8 kHz */

static short signal[NSAMP];
static short quiet[NSAMP];

int
main(void)
{
	static int idle[64], data[64];
	int rc = 0;
	int bits;
	int i;

	for (i = 0; i < 64; i++) {
		idle[i] = 1;			/* continuous mark */
		/* Runs of both, long enough that the settle counter tracks. */
		data[i] = (i / 2) & 1;
	}

	/*
	 * Carrier first, then data.  Ten blocks of detected 390 Hz is the
	 * gate, and FPM_TONE_detect works on a running average, so the idle
	 * run has to be substantial -- a few hundred samples would leave both
	 * demodulators waiting and the test would prove nothing.
	 */
	generate(signal, NSAMP / 3, idle, 64);
	generate(signal + NSAMP / 3, NSAMP - NSAMP / 3, data, 64);
	memset(quiet, 0, sizeof(quiet));

	diff_begin("BwChDem: acquiring carrier and demodulating");
	bits = run("filtered samples[%ld]", signal, NSAMP, 160, 100000);
	printf("  160-sample blocks: %d bits out\n", bits);
	rc |= diff_end();

	diff_begin("BwChDem: other block sizes");
	/*
	 * The quarter-bit table has 12 entries of 26 or 27 samples, so a block
	 * boundary almost never coincides with a decision.  Sizes that are and
	 * are not multiples of that pattern exercise different interleavings
	 * of the two.
	 */
	run("block 80[%ld]", signal, NSAMP, 80, 100000);
	run("block 107[%ld]", signal, NSAMP, 107, 100000);
	run("block 320[%ld]", signal, NSAMP, 320, 100000);
	rc |= diff_end();

	diff_begin("BwChDem: silence, and giving up");
	/*
	 * Silence never brings carrier up, so this exercises the acquisition
	 * timeout rather than the silence charge -- the two are different
	 * paths to the same return code and the counters below check both
	 * were reached.
	 */
	run("silent samples[%ld]", quiet, NSAMP, 16, 40);
	rc |= diff_end();

	diff_begin("BwChDem: coverage");
	diff_eq_int("it waited for carrier", saw_waiting > 0, 1, 0);
	diff_eq_int("carrier came up", saw_demodulating > 0, 1, 0);
	diff_eq_int("bits were demodulated", saw_bits > 0, 1, 0);
	diff_eq_int("a one was received", saw_one > 0, 1, 0);
	diff_eq_int("a zero was received", saw_zero > 0, 1, 0);
	diff_eq_int("it gave up on a dead line", saw_given_up > 0, 1, 0);
	printf("  waiting %d, demodulating %d, gave up %d, ones %d, zeros %d\n",
	       saw_waiting, saw_demodulating, saw_given_up, saw_one, saw_zero);
	rc |= diff_end();

	return rc;
}
